// this file is the dir to mapfile for help here
// by dongsw 2003

mapping maps = ([
  "/d/beijing/" : "beijing.map",
  "/d/canyon/" : "xixia.map",
  "/d/bak-huashan/" : "huashan.map",
  "/d/chengdu/" : "chengdu.map",
  "/d/choyin/" : "choyin.map",
  "/d/chuenyu/" : "heisongbao.map",
  "/d/cloud/" : "yiyun.map",
  "/d/emei/" : "emei.map",
  "/d/gaibang/" : "yueyang.map",
  "/d/gumu/" : "gumu.map",
  "/d/hangzhou/" : "hangzhou.map",
  "/d/heimuya/" : "rysj.map",
  "/d/hua/" : "xiankelai.map",
  "/d/huashan/" : "huashan.map",
  "/d/jingcheng/" : "jingcheng.map",
  "/d/latemoon/" : "latemoon.map",
  "/d/leigu/" : "leigu.map",
  "/d/lingjiu/" : "lingjiu.map",
  "/d/mingjiao/" : "mingjiao.map",
  "/d/newb/" : "newbie.map",
  "/d/oldpine/" : "xueting.map",
  "/d/qiankun/" : "qiankun.map",
  "/d/qingcheng/" : "qingcheng.map",
  "/d/quanzhen/" : "quanzhen.map",
  "/d/quanzhou/" : "quanzhou.map",
  "/d/resort/" : "resort.map",
  "/d/shaolin/" : "shaolin.map",
  "/d/snow/" : "xueting.map",
  "/d/suzhou/" : "suzhou.map",
  "/d/taishan/" : "taishan.map",
  "/d/tangmen/" : "tangmen.map",
  "/d/taoguan/" : "maoshan.map",
  "/d/taohua/" : "taohua.map",
  "/d/village/" : "village.map",
  "/d/waterfog/" : "tianxie.map",
  "/d/wudang/" : "wudang.map",
  "/d/xanadu/" : "shanzhuang.map",
  "/d/xingxiu/" : "xingxiu.map",
  "/d/xixia/" : "xixia.map",
  "/d/xueshan/" : "chuixue.map",
  "/d/yueyang/" : "yueyang.map",
  "/d/xizang/" : "lasa.map",
]);
mapping xizang_maps = ([
  "/d/xizang/class/budala/" : "budalagong.map",
  "/d/xizang/class/gold_wh/" : "jinlunsi.map",
  "/d/xizang/class/snow_mnt/" : "xueshan.map",
  "/d/xizang/class/dazhao/" : "lasa.map",
]);
  
