inherit SKILL;

mapping *quest = ({
	([	"quest":	"昭仪",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"绣花鞋",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"柳玉刀",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"傻姑",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"采花妞",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	-1,
	]),

	([	"quest":	"紫花瓣儿",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	-1,
	]),

	([	"quest":	"牧羊人",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"羊鞭",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"[1;35m柳永[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"宾奴",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"道正禅师",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"[35m富人[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	-1,
	]),

	([	"quest":	"灰布镶边袈裟",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"教授",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"扫地僧",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"猴子",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	-1,
	]),

	([	"quest":	"小周",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"小陈",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"李老板",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"陶老大",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"阿红",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"花无机",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"老王",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"水灵光",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"圆春",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"[35m星宿派[2;37;0m[33m鼓手[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	-1,
	]),

	([	"quest":	"铜鼓",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	-1,
	]),

	([	"quest":	"贵公子",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"玉带冠",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"孙长汉",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"小绵羊",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"青衣家丁",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	-1,
	]),

	([	"quest":	"六角锤",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	-1,
	]),

	([	"quest":	"唐竹",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	-1,
	]),

	([	"quest":	"陌生人马铁嘴",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"柴金彩",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"响尾蛇",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"老人",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"怜儿",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"观光客",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	0,
	]),

	([	"quest":	"[1;36m青布衣衫[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	-1,
	]),

	([	"quest":	"阿昌",
		"quest_type":	"杀",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

});
mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
