inherit SKILL;

mapping *quest = ({
        ([      "quest":                "野狗",
                "quest_type":           "杀",
                "time":		  511,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  2,
                "score"	:	  1,
        ]),
        ([      "quest":                "逄义",
                "quest_type":           "杀",
                "time":		  346,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  6,
                "score"	:	  1,
        ]),
        ([      "quest":                "媒婆",
                "quest_type":           "杀",
                "time":		  858,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  2,
                "score"	:	  1,
        ]),
        ([      "quest":                "魏无极",
                "quest_type":           "杀",
                "time":		  661,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  3,
                "score"	:	  1,
        ]),
        ([      "quest":                "苦力",
                "quest_type":           "杀",
                "time":		  495,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  2,
                "score"	:	  1,
        ]),
        ([      "quest":                "庙祝",
                "quest_type":           "杀",
                "time":		  167,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  4,
                "score"	:	  1,
        ]),
        ([      "quest":                "店小二",
                "quest_type":           "杀",
                "time":		  321,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  4,
                "score"	:	  1,
        ]),
        ([      "quest":                "收破烂的",
                "quest_type":           "杀",
                "time":		  886,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  6,
                "score"	:	  1,
        ]),
        ([      "quest":                "农夫",
                "quest_type":           "杀",
                "time":		  712,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  7,
                "score"	:	  1,
        ]),
        ([      "quest":                "老农夫",
                "quest_type":           "杀",
                "time":		  713,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  8,
                "score"	:	  1,
        ]),
        ([      "quest":                "乞丐",
                "quest_type":           "杀",
                "time":		  758,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  2,
                "score"	:	  1,
        ]),
        ([      "quest":                "疯狗",
                "quest_type":           "杀",
                "time":		  600,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  4,
                "score"	:	  1,
        ]),
        ([      "quest":                "醉汉",
                "quest_type":           "杀",
                "time":		  377,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  10,
                "score"	:	  1,
        ]),
        ([      "quest":                "武馆弟子",
                "quest_type":           "杀",
                "time":		  515,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  5,
                "score"	:	  1,
        ]),
        ([      "quest":                "樵夫",
                "quest_type":           "杀",
                "time":		  585,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  8,
                "score"	:	  1,
        ]),
        ([      "quest":                "王铁匠",
                "quest_type":           "杀",
                "time":		  845,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  9,
                "score"	:	  1,
        ]),
        ([      "quest":                "杜宽",
                "quest_type":           "杀",
                "time":		  793,
                "exp_bonus"	:	  5,
                "pot_bonus"	:	  7,
                "score"	:	  1,
        ]),
        ([      "quest":                "柳绘心",
                "quest_type":           "杀",
                "time":		  706,
                "exp_bonus"	:	  6,
                "pot_bonus"	:	  6,
                "score"	:	  1,
        ]),
        ([      "quest":                "杨掌柜",
                "quest_type":           "杀",
                "time":		  411,
                "exp_bonus"	:	  6,
                "pot_bonus"	:	  4,
                "score"	:	  1,
        ]),
        ([      "quest":                "李火狮",
                "quest_type":           "杀",
                "time":		  260,
                "exp_bonus"	:	  8,
                "pot_bonus"	:	  9,
                "score"	:	  1,
        ]),
        ([      "quest":                "刘安禄",
                "quest_type":           "杀",
                "time":		  432,
                "exp_bonus"	:	  25,
                "pot_bonus"	:	  7,
                "score"	:	  1,
        ]),
        ([      "quest":                "安惜迩",
                "quest_type":           "杀",
                "time":		  883,
                "exp_bonus"	:	  205,
                "pot_bonus"	:	  22,
                "score"	:	  1,
        ]),
});
mapping query_quest()
{
  return quest[random(sizeof(quest))];
}
