inherit SKILL;
mapping *quest = ({
        ([      "quest":        "[35m离别钩[2;37;0m",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
/*
        ([      "quest":        "[32m孔雀翎[2;37;0m",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
*/
        ([      "quest":        "孔雀图",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
/*
        ([      "quest":        "[1;31m霸王枪[2;37;0m",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
*/
        ([      "quest":        "[37m多情环[2;37;0m",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
/*
        ([      "quest":        "箱子",
                "quest_type":   "寻",
                "exp_bonus":    200,
                "shen_type":    999,
        ]),
*/
        ([      "quest":        "[1;32m长生剑[2;37;0m",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
        ([      "quest":        "白玉琴",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
        ([      "quest":        "黑色火药",
                "quest_type":   "寻",
                "exp_bonus":    60,
                "shen_type":    999,
        ]),
        ([      "quest":        "铁血大旗",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
        ([      "quest":        "锦册",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
        ([      "quest":        "[1;31m宣花巨斧[2;37;0m",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
        ([      "quest":        "嫁衣神功",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
        ([      "quest":        "树叶",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
        ([      "quest":        "遁甲天书",
                "quest_type":   "寻",
                "exp_bonus":    20,
                "shen_type":    999,
        ]),
        ([      "quest":        "软猥甲",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "桃枝",
                "quest_type":   "寻",
                "exp_bonus":    10,
                "shen_type":    999,
        ]),
        ([      "quest":        "[1;31m屠龙刀[2;37;0m",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "游龙剑",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "九花玉露丸",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "蛤蟆肉",
                "quest_type":   "寻",
                "exp_bonus":    20,
                "shen_type":    999,
        ]),
        ([      "quest":        "通天草",
                "quest_type":   "寻",
                "exp_bonus":    10,
                "shen_type":    999,
        ]),
        ([      "quest":        "过招要旨",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "踏雪无痕",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "[31m驻颜丹[2;37;0m",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "暗器手法",
                "quest_type":   "寻",
                "exp_bonus":    20,
                "shen_type":    999,
        ]),
        ([      "quest":        "遗书",
                "quest_type":   "寻",
                "exp_bonus":    80,
                "shen_type":    999,
        ]),
        ([      "quest":        "圣火令",
                "quest_type":   "寻",
                "exp_bonus":    10,
                "shen_type":    999,
        ]),
        ([      "quest":        "华山剑谱",
                "quest_type":   "寻",
                "exp_bonus":    30,
                "shen_type":    999,
        ]),
        ([      "quest":        "伊犁马",
                "quest_type":   "寻",
                "exp_bonus":    20,
                "shen_type":    999,
        ]),
        ([      "quest":        "白玉琵琶",
                "quest_type":   "寻",
                "exp_bonus":    30,
                "shen_type":    999,
        ]),
        ([      "quest":        "焦尾琴",
                "quest_type":   "寻",
                "exp_bonus":    20,
                "shen_type":    999,
        ]),
        ([      "quest":        "圣经",
                "quest_type":   "寻",
                "exp_bonus":    30,
                "shen_type":    999,
        ]),
        ([      "quest":        "菩提子",
                "quest_type":   "寻",
                "exp_bonus":    200,
                "shen_type":    999,
        ]),
        ([      "quest":        "伏魔刀",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
        ([      "quest":        "金刚罩",
                "quest_type":   "寻",
                "exp_bonus":    100,
                "shen_type":    999,
        ]),
        ([      "quest":        "石板",
                "quest_type":   "寻",
                "exp_bonus":    20,
                "shen_type":    999,
        ]),
        ([      "quest":        "薄绢",
                "quest_type":   "寻",
                "exp_bonus":    20,
                "shen_type":    999,
        ]),
        ([      "quest":        "风云手手法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "如来千叶手手法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "大金刚拳法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "罗汉拳法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "般若掌法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "散花掌法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "龙爪功法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "鹰爪功法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "拈花指法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "一指禅功",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "慈悲刀法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "修罗刀法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "韦陀棍法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "醉棍棍法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "无常杖法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "普渡杖法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "伏魔剑法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":        "达摩剑法",
                "quest_type":   "寻",
                "exp_bonus":    50,
                "shen_type":    999,
        ]),
        ([      "quest":                "「嘉德文选」",
                "quest_type":           "寻",
                "exp_bonus":            25,
        	"shen_type":	999,
	]),
        ([      "quest":                "桃木箱",
                "quest_type":           "寻",
                "exp_bonus":            25,
        	"shen_type":	999,
	]),
        ([      "quest":                "「白杨经」",
                "quest_type":           "寻",
                "exp_bonus":            25,
        	"shen_type":	999,
	]),
        ([      "quest":                "银簪",
                "quest_type":           "寻",
                "exp_bonus":            25,
        	"shen_type":	999,
	]),
        ([      "quest":                "「水龙图注」",
                "quest_type":           "寻",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),
        ([      "quest":                "「寒士列传」",
                "quest_type":           "寻",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),
        ([      "quest":                "「佾风斋诗集」",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),
        ([      "quest":                "「乡书」",
                "quest_type":           "寻",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),
        ([      "quest":                "「古文志」",
                "quest_type":           "寻",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),
        ([      "quest":                "「说律」",
                "quest_type":           "寻",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),
        ([      "quest":                "「梁父文集」",
                "quest_type":           "寻",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),
        ([      "quest":                "「太公辩」",
                "quest_type":           "寻",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),
        ([      "quest":                "「九韬」",
                "quest_type":           "寻",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),
        ([      "quest":                "竹子",
                "quest_type":           "寻",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),
        ([      "quest":                "竹蜻蜓",
                "quest_type":           "寻",
                "exp_bonus":            60,
        	"shen_type":	999,
	]),
        ([      "quest":                "女儿红",
                "quest_type":           "寻",
                "exp_bonus":            20,
        	"shen_type":	999,
	]),
        ([      "quest":                "女儿红",
                "quest_type":           "寻",
                "exp_bonus":            20,
        	"shen_type":	999,
	]),
        ([      "quest":                "[1;31m丝罗巾[2;37;0m",
                "quest_type":           "寻",
                "exp_bonus":            30,
        	"shen_type":	999,
	]),
        ([      "quest":                "[1;36m玛瑙手镯[2;37;0m",
                "quest_type":           "寻",
                "exp_bonus":            100,
        	"shen_type":	999,
	]),
        ([      "quest":                "玉佩",
                "quest_type":           "寻",
                "exp_bonus":            60,
        	"shen_type":	999,
	]),
        ([      "quest":                "紫罗鸳鸯荷包",
                "quest_type":           "寻",
                "exp_bonus":            40,
        	"shen_type":	999,
	]),
        ([      "quest":                "紫罗鸳鸯荷包",
                "quest_type":           "寻",
                "exp_bonus":            40,
        	"shen_type":	999,
	]),
        ([      "quest":                "碧玉胡刀",
                "quest_type":           "寻",
                "exp_bonus":            80,
        	"shen_type":	999,
	]),
        ([      "quest":                "[32m真武剑[2;37;0m",
                "quest_type":           "寻",
                "exp_bonus":            100,
        	"shen_type":	999,
	]),
        ([      "quest":                "鸡汤",
                "quest_type":           "寻",
                "exp_bonus":            60,
        	"shen_type":	999,
	]),
        ([      "quest":                "字画",
                "quest_type":           "寻",
                "exp_bonus":            60,
        	"shen_type":	999,
	]),
        ([      "quest":                "象牙骰子",
                "quest_type":           "寻",
                "exp_bonus":            60,
        	"shen_type":	999,
	]),
        ([      "quest":                "[30m黑水伏蛟[2;37;0m",
                "quest_type":           "寻",
                "exp_bonus":            50,
        	"shen_type":	999,
	]),

});
mapping query_quest()
{
  return quest[random(sizeof(quest))];
}
