inherit SKILL;

mapping *quest = ({
	([	"quest":	"[35m蟒蛇[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31m林老板[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"水烟阁红衣武士",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"牛皮靴",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"水烟阁武士氅",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"鲜红金乌冠",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"萧升",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"天邪虎",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"萧萧",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"陆得财",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"清法比丘",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"塔僧",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"舍利子",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32m程灵素[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"阴宾",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"道尘禅师",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"道一禅师",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"[1;31m轻红罗衣[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31m轻红罗纱[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"孙天灭",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"莫不收",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"李莫愁",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"拂尘",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"青色道袍",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"阿善",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"[32m绿衣少女[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32m绿鞋[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32m绿镯[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32m绿衣[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32m绿带[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32m绿帽[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[32m绿巾[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"道成禅师",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"快活三",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"青衣武士",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"铁甲",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"大队长",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"青铜战盔",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"苗郁手",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"钻石胸针",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"耳环",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"颜垣",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"黄色长衫",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"岳灵珊",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"绿色长裙",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"冯铁匠",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"道觉禅师",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"[35m紫衣少女[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m紫鞋[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m紫镯[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m紫衣[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m紫带[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m紫帽[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[35m紫巾[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"张三",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"蒙面头罩",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"道果禅师",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"道相禅师",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"守寺僧兵",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"淳于怀太",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"蛇鳞皮鞭",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"蓝筱薇",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"昭蓉",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"玉竹剑",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"银翅金簪",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[36m青绫绸裙[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"金仪彤",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;35m珍珠项□[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"龙韶吟",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"武将",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"谷虚道长",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"道品禅师",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"老板",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"小昭",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"[33m老虎[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"唐方",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"周伯通",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"巡山弟子",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	1,
	]),

	([	"quest":	"酒店女老板",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;35m粉红布衫[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"[33m心眉和尚[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;35m公主[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	-1,
	]),

	([	"quest":	"老年弈者",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;35m段玉[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;37m曹子建[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[30m张骥[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
