#include <ansi.h>
inherit SKILL;

mapping *quest = ({
	([	"quest":	"卖饼大叔",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	

	([	"quest":	"乾瘪老太婆",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"卖包子的",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"官家小姐",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"妇人",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"丫□",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"书生",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"蚂蚁",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"蝴蝶",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"蛐蛐",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"信鸽",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"小娟",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"苍蝇",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"李师师",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"茶叶",
		"quest_type":	"寻0",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"茶博士",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"醉汉",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"工匠的小孩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"小孩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"老公公",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"老婆婆",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"沈万年",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"工匠",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"采石工",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"乞丐",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"塔祝",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"收破烂的",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"樵夫",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[35m鲤鱼[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"店小二",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"老板娘",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"败家子",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"农民",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33m卖花小女孩[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"青衣家人",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33m店小二[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"葛六",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	

	([	"quest":	"老鼠肉",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	([	"quest":	"[35m糖醋鱼[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	([	"quest":	"[35m香糕[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	
	([	"quest":	"农夫",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"媒婆",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"魏无极",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"苦力",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[30m店小二[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[35m小贩[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"长剑",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"青布僧衣",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"渔夫",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	([	"quest":	"小贩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"女孩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"老农夫",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"小猴",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"[30m小猴[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"老大娘",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"武馆弟子",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"维吾尔族妇女",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"旧书",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"粗布衣",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"布衣",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"牛皮酒袋",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"蓑衣",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"草鞋",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"白色道袍",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"筛子",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"铁□",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

/*	([	"quest":	"黑色长袍",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),*/

	([	"quest":	"轻罗绸衫",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"银簪",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"菜刀",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"陶壶",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"匕首",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"粉红绸衫",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"大红绸衫",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"「九韬」",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"粉红布衫",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"破烂的粉红布衫",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"铁斧",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"维吾尔族长袍",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"[33m浣纱女孩[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[32m舞姬[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	([	"quest":	"小童",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"婢女",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33m女孩[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"穷汉",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"老鼠",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"蜜蜂",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"绸衣",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[35m纱[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"布裙",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"男孩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"孤魂野鬼",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"村长",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"野狗",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31m女孩[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31m店小二[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"丫鬟",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"进香客",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33m游人[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33m行人[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[30m妇人[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"小白兔",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"小蜜蜂",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"从寿衣撕下的布条",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"乌鸦",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	([	"quest":	"挑夫",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	([	"quest":	"农妇",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"毒蛇",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"翠花",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"王铁匠",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"铁锤",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"陈阿婆",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"汤掌柜",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"家丁",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"柳玉儿",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"金丝雀",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"小金鼠",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"野兔",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"蛤蟆",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),


	([	"quest":	"净苦",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"净难",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"净痛",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"[31m点点[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"白玉琵琶",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"戚四",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31m红衣少女[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"净慈",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"[31m大老鼠[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"[31m红鞋[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31m红镯[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31m红衣[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31m红带[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31m红帽[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[31m红巾[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"焦尾琴",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	
	([	"quest":	"蜘蛛",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"疯狗",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"小流氓",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"小喽罗",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"土匪",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"短剑",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"茶工",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"茶叶",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"皮衣",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"小羊羔",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	([	"quest":	"游客",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"[33m小鹿[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"长鞭",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"伙计",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"采药人",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"天山雪莲",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"药锄",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"女佣人",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"鸡毛",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"大狼狗",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"杂货贩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"飞镖",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"地痞",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"小土匪",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"道长",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	([	"quest":	"小孩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"布衣",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"蜜蜂",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"金丝雀",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"卖包子的",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"小女孩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"女孩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"小贩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"小尼姑",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"青城弟子",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"女侍",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"匕首",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"镖局弟子",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"仆人",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"林镇南",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"尼姑",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"海公公",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"[36m青城弟子[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"恶少",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	-1,
	]),

	([	"quest":	"毒蛇",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;36m店小二[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),
	([	"quest":	"[31m老板[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33m西欧游客[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;35m春游女孩[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"济公和尚",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"老妇人",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"香香",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;35m百叶裙[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;36m美能达７００Ｓｉ[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;37m西服[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;37m长衫[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;36m游人[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;37m飘柔[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"[1;35m蝶裙[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	1,
	]),

	([	"quest":	"[31m春游女孩[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),


	([	"quest":	"[1;37m居民[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;37m春游女子[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[33m彩裙[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"渔家少女",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"春游女孩",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"小混混",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"[1;36m牛崽衣[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"烤鸡腿",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

});

mapping quest_one = 
        ([      "quest":        "烤鸡腿",
                "quest_type":   "寻",
                "exp_bonus":    10,
                "shen_type":    0,
        ]);

mapping query_quest()
{
	object room;

	if( random(10) )
	{
		room = "/adm/daemons/dynamicd"->get_random_room_npc();
		if( objectp(room) )
		{
			if( room->is_character() )
			{
				quest_one["quest"] = room->query("name");
				quest_one["quest_type"] = "寻人";	
			}
			else
			{
				quest_one["quest"] = room->query("short");
                        	quest_one["quest_type"] = "探路";
			}
			quest_one["exact"] = base_name(room);
			return quest_one;
		}	
	}
	else
        	return quest[random(sizeof(quest))];
}
