#include <ansi.h>
inherit SKILL;

mapping *quest = ({

	([	"quest":	"[31m媒婆[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	
	([	"quest":	"李斧头",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"柳淳风",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"狼皮雪靴",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"白缨冠",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"丝绸马褂",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"澄和",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"澄信",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),
	
	
	([	"quest":	"俞莲舟",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"神斧力士",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31m宣花巨斧[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"朦胧鬼影",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),

	([	"quest":	"乌檀木刀",
		"quest_type":	"寻",
		"exp_bonus":	120,
		"shen_type":	0,
	]),

	([	"quest":	"澄灵",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"澄灭",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"澄尚",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"澄行",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"澄欲",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"[32m方天画戟[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[30m降魔杵[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;37m亮银枪[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	80,
		"shen_type":	0,
	]),
/*
	([	"quest":	"老张",
		"quest_type":	"杀",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
*/
	([	"quest":	"澄寂",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"常老大",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"竹管",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"狼皮披风",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"陆乘风",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"左全",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"胭松",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	-1,
	]),
	
	([	"quest":	"完颜亮",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	
	([	"quest":	"[36m佩刀[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	
	([	"quest":	"何不净",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"玄慈大师",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"鲍大楚",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"罗烈",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"上官云",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"桑三娘",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"王诚",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"葛停香",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"长戟",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"童百熊",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"贾布",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"林忌",
		"quest_type":	"杀",
		"exp_bonus":	130,
		"shen_type":	0,
	]),

	([	"quest":	"三清神冠",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"天师道袍",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"七星翻云靴",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31m咒剑王□[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"小情圣",
		"quest_type":	"杀",
		"exp_bonus":	130,
		"shen_type":	0,
	]),

	([	"quest":	"[35m“梦特娇围巾”[2;82;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	([	"quest":	"[37m钢剑[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	
	
	([	"quest":	"[35m杨排风[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"严廷殷",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;37mψ破 残 奇 剑ψ[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[31m火 云 [1;34m战 甲[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"潘军禅",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;37m邪剑穿灵[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	

	([	"quest":	"萧辟尘",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;36m吹雪残云靴[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;36m吹雪残云衣[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;36m吹雪残云带[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;36m吹雪残云巾[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"铁血大旗",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"唐宏",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"刘处玄",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"林平之",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静风师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静心师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静虚师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静玄师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静照师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静真师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"李明霞",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"苏梦清",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"吉人英",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"方碧琳",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静慈师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"贝锦仪",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静道师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静和师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静慧师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静迦师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静空师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"静闲师太",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"赵灵珠",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"[1;37m方怡[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	([	"quest":	"[1;37m苏芮[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"[35m紫袍老人[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"[1;37m金成武[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"[32m碧玉刀[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"[33m宁馨[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"[1;37m纪嫣然[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"吊睛白额大虫",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"韦小宝",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"[35m燕七[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"[1;35m郭大路[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"庄铮",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	([	"quest":	"辛然",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	([	"quest":	"闻苍松",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
//	([	"quest":	"赵敏",
//		"quest_type":	"杀",
//		"exp_bonus":	110,
//		"shen_type":	0,
//	]),
	([	"quest":	"张中",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"说不得",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	([	"quest":	"冷谦",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	([	"quest":	"唐洋",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	([	"quest":	"彭莹玉",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"白虎之铠",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"皮腰带",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	([	"quest":	"狼牙棒",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"[33m土蕃武士[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"大铁杆",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

	([	"quest":	"钟灵",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"素绸衫",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"木婉清",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	-1,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
