#include <ansi.h>
inherit SKILL;

mapping *quest = ({


	([	"quest":	"军刀",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),
	([	"quest":	"[34m竹叶青[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
	([	"quest":	"[31m女儿红[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
/*	([	"quest":	"青葫芦",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	0,
	]),
*/	
	([	"quest":	"面具",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	0,
	]),
	([	"quest":	"[33m蟹黄包子[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	0,
	]),	
	([	"quest":	"金项链",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	1,
	]),
	([	"quest":	"绣花针",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	1,
	]),
	([	"quest":	"金戒指",
		"quest_type":	"寻",
		"exp_bonus":	30,
		"shen_type":	1,
	]),

	([	"quest":	"[1;33m束发嵌宝紫金冠[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
	([	"quest":	"[30m铁背心[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36m石青起花八团倭缎排穗褂[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
	([	"quest":	"[1;33m二龙抢珠金抹额[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
	([	"quest":	"[1;31m百蝶穿花大红箭袖[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
	([	"quest":	"[1;33m五彩[2;37;0m[1;37m丝攒[2;37;0m[1;31m花结[2;37;0m[1;32m长穗[2;37;0m[36m宫绦[2;37;0m", 
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
	([	"quest":	"知客道长",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"[30m恶霸[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"赵狗儿",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[31m门房[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"清观比丘",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"清乐比丘",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"清为比丘",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"清缘比丘",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"白布黑边袈裟",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"剑客",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"镖师",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"大红尼袍",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"鸨母",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
  /*
	([	"quest":	"极乐逍遥散",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
	([	"quest":	"『星宿毒经〖上册〗』",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
*/
	([	"quest":	"小翠",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"绣花小鞋",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"细剑",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36m青衣少女[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36m青鞋[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36m青镯[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36m青衣[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36m青带[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36m青帽[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[36m青巾[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"小兵",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"老兵",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"护林僧兵",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"戒刀",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"郑屠夫",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"解牛刀",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"牛皮束带",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"青衣少女",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[30m梁万良[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"青衣",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"青带",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"王小二",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"清无比丘",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"城卫",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"三环禅杖",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"大红僧袍",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"芙云",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"空空儿",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
	([	"quest":	"木人",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"园丁",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"清善比丘",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"清闻比丘",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"清晓比丘",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),
/*
	([	"quest":	"欧阳克",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),
  */
	([	"quest":	"老婆子",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m黄衣少女[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m黄鞋[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m黄镯[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m黄衣[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m黄带[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m黄帽[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"[33m黄巾[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"厨子",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"碧玉刀",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"烤山猪肉",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"人皮酒袋",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"虚明",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"弈者",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"棋子",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"野猪",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"草原狼",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

	([	"quest":	"巨型犬",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"唐白",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

	([	"quest":	"秀才",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"游方郎中",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	1,
	]),

	([	"quest":	"[31m小甜[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),

/*	([	"quest":	"[36m轻罗绸衫[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	60,
		"shen_type":	0,
	]),*/

	([	"quest":	"紫花瓣儿",
		"quest_type":	"寻",
		"exp_bonus":	40,
		"shen_type":	0,
	]),

	([	"quest":	"珠宝商",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	
	([	"quest":	"蒙面人",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	0,
	]),
	
	([	"quest":	"流氓老大",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),
	
	([	"quest":	"侍剑",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),
	([	"quest":	"司棋",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),
	([	"quest":	"紫娟",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),
	([	"quest":	"聆琴",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),
	([	"quest":	"听雨",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),
	([	"quest":	"老妇人",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),
	([	"quest":	"芦苇",
		"quest_type":	"寻",
		"exp_bonus":	10,
		"shen_type":	0,
	]),

	([	"quest":	"鱼",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),
	([	"quest":	"虾",
		"quest_type":	"杀",
		"exp_bonus":	60,
		"shen_type":	-1,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
