inherit SKILL;

mapping *quest = ({
        ([      "quest":                "小翠",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            95,
                "pot_bonus":            59,
                "score" :               20
        ]),
        ([      "quest":                "弈者",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            95,
                "pot_bonus":            59,
                "score" :               20
        ]),
        ([      "quest":                "郑屠夫",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            59,
                "pot_bonus":            59,
                "score" :               20
        ]),
        ([      "quest":                "趟子手",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            95,
                "pot_bonus":            59,
                "score" :               20
        ]),
        ([      "quest":                "苍蝇",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            95,
                "pot_bonus":            59,
                "score" :               20
        ]),
        ([      "quest":                "宝官",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            85,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "药僧",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            85,
                "pot_bonus":            58,
                "score" :               20
        ]),
        ([      "quest":                "船夫",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            85,
                "pot_bonus":            58,
                "score" :               20
        ]),
        ([      "quest":                "护寺武僧",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            85,
                "pot_bonus":            58,
                "score" :               20
        ]),
        ([      "quest":                "知客僧",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            85,
                "pot_bonus":            58,
                "score" :               20
        ]),
        ([      "quest":                "知饭僧",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            85,
                "pot_bonus":            58,
                "score" :               20
        ]),
        ([      "quest":                "烧饭僧",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            58,
                "pot_bonus":            58,
                "score" :               20
        ]),
        ([      "quest":                "化缘和尚",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            80,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "彩衣少女",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            80,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "鸨母",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            80,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "贵公子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "护院",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "土匪喽罗",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "大岩蛭",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "商人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "绵羊",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "李火狮",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "菜贩",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "昭仪",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            80,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "僵尸侍者",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "岩蛭",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            55,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "肥岩蛭",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "跛僧人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "厨师",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "杂货贩",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "袭人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            22,
                "score" :               20
        ]),
        ([      "quest":                "明心",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "老道士",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "家丁",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            52,
                "score" :               20
        ]),
        ([      "quest":                "土匪",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "大胖子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            52,
                "score" :               20
        ]),
        ([      "quest":                "登徒子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "卖饼大叔",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "丫□",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "书生",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "采石工",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "汤掌柜",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "家丁",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "进香客",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "玄真",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "玄和",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "疯狗",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "王铁匠",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "樵夫",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "沈万年",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "小孩",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            15,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "工匠",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "老婆婆",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "老公公",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
       ([      "quest":                "武馆弟子",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               20
        ]),
       ([      "quest":                "樵夫",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               20
        ]),
        ([      "quest":                "棋子",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "蝴蝶",
                "quest_type":           "杀",
                "time":                 900,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
       ([      "quest":                "破弯刀",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "破剑",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
        ([      "quest":                "小羊羔",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               300
        ]),
       ([      "quest":                "木刀",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "竹剑",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            15,
                "score" :               30
        ]),
       ([      "quest":                "白棋子",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            5,
                "score" :               30
        ]),
        ([      "quest":                "菜贩",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "厨师",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "厨师",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "登徒子",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "大胖子",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "伙计",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "苦力",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "流氓",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "姨太太",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "澡堂老板",
                "quest_type":           "杀",
                "time":                 700,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "乞丐",               
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            20,
                "pot_bonus":            5,
                "score" :               10
        ]),
        ([      "quest":                "魔法入门",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "牛皮酒袋",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "烤鸡腿",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "匕首",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "包子",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "符咒简介",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "红玫瑰",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "蓝天鹅",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "红玫瑰",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "红玫瑰",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "黄玫瑰",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "白茶花",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "紫罗兰",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "白茶花",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "黑牡丹",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "绳子",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "菜刀",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            15,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "陶壶",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            15,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "鲤鱼",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "粉红绸衫",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "舞蝶彩衫",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "极乐逍遥散",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            15,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "匕首",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "茶叶",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "布袋",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "麻绳",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            15,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "棋子",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "化尸粉",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "飞镖",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "蓑衣",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "草鞋",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "鸡腿骨头",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
