inherit SKILL;

mapping *quest = ({
        ([      "quest":                "乞丐",               
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               10
        ]),
        ([      "quest":                "疯狗",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               20
        ]),
        ([      "quest":                "野狗",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            20,
                "pot_bonus":            10,
                "score" :               20
        ]),
        ([      "quest":                "醉汉",
                "quest_type":           "杀",
                "time":                 600,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "农夫",
                "quest_type":           "杀",
                "time":                 900,
                "exp_bonus":            40,
                "pot_bonus":            40,
                "score" :               20
        ]),
        ([      "quest":                "旧书",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "大老鼠",
                "quest_type":           "杀",
                "time":                 900,
                "exp_bonus":            40,
                "pot_bonus":            40,
                "score" :               20
        ]),
       ([      "quest":                "收破烂的",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            40,
                "score" :               20
        ]),
       ([      "quest":                "王铁匠",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            40,
                "pot_bonus":            40,
                "score" :               20
        ]),
       ([      "quest":                "魏无极",
                "quest_type":           "杀",
                "time":                 130,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               20
        ]),
       ([      "quest":                "武馆弟子",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               20
        ]),
       ([      "quest":                "樵夫",
                "quest_type":           "杀",
                "time":                 300,
                "exp_bonus":            10,
                "pot_bonus":            10,
                "score" :               20
        ]),
        ([      "quest":                "棋子",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "蝴蝶",
                "quest_type":           "杀",
                "time":                 900,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "菜贩",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "厨师",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "厨师",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "登徒子",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "大胖子",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "伙计",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "车马店老板",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "苦力",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "流氓",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "姨太太",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "澡堂老板",
                "quest_type":           "杀",
                "time":                 800,
                "exp_bonus":            40,
                "pot_bonus":            20,
                "score" :               20
        ]),
        ([      "quest":                "魔法入门",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "牛皮酒袋",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "烤鸡腿",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "匕首",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "布袋",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "包子",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "符咒简介",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            5,
                "pot_bonus":            5,
                "score" :               20
        ]),
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
