inherit SKILL;

mapping *quest = ({
	([	"quest":	"蓝小蝶",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),
/*	([	"quest":	"净悲",
		"quest_type":	"杀",
		"exp_bonus":	10,
		"shen_type":	1,
	]),*/


	([	"quest":	"[1;36m绣花针[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"颜慧如",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;31m魏不悔[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"[33m王铁匠[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"老板男人",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"毒药镖",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"密函",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"包子",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"护山使者",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"疯老头子",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"太阴八卦袍",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"蓝雨梅",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[32m护院[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"哑仆",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"上官钰翎",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"冰玉戒指",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"李白",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"钢剑",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"游侠儿",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"扬中顺",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"戴宗",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"秦报国",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"托钵僧",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"柳绘心",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m橙衣少女[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m橙鞋[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m橙镯[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m橙衣[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m橙带[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m橙帽[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m橙巾[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"黑冠巨蟒",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"江百胜",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"见钱开",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"王二麻",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"[31m野猪[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"巡捕",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"护法袈裟",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"玉石琵琶",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"阿紫",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

/*	([	"quest":	"清心散",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),
*/
	([	"quest":	"官兵",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"军服",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"裘万家",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"梢公",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"船篙",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"秀才",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"小队长",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"老队长",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"何师我",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"李四",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"[33m趟子手[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"秦玉",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"长枪",
		"quest_type":	"寻",
		"exp_bonus":	70,
		"shen_type":	1,
	]),

	([	"quest":	"梦玉楼",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"练功弟子",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"唐圆",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"骏马",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"守山弟子",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"采茶少女",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	0,
	]),

	([	"quest":	"[31m扫地和尚[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;35m贾雨村[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
