#include <ansi.h>
inherit SKILL;

mapping *quest = ({

	([	"quest":	"铁中棠",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	
	([	"quest":	"阮欣郁",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"黎生",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"[35m穆桂英[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	130,
		"shen_type":	1,
	]),

	([	"quest":	"曲灵风",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"谭处端",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"丘处机",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"侍卫",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"金庸",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"京城地图",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"马俱为",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"余洪兴",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),


	([	"quest":	"彭有敬",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),
	([	"quest":	"黄药师",
		"quest_type":	"杀",
		"exp_bonus":	130,
		"shen_type":	0,
	]),
	
	([	"quest":	"[32m玉箫[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	0,
	]),
	
	([	"quest":	"卜鹰",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	0,
	]),

	([	"quest":	"弯刀",
		"quest_type":	"寻",
		"exp_bonus":	120,
		"shen_type":	0,
	]),

	([	"quest":	"韦一笑",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),

	([	"quest":	"玄苦大师",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	1,
	]),

	([	"quest":	"玄难大师",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	1,
	]),

	([	"quest":	"简长老",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"[33m秦歌[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"[33m多情刀[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"梁长老",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"鲁有脚",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	0,
	]),

	([	"quest":	"玄悲大师",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	1,
	]),

	([	"quest":	"成不优",
		"quest_type":	"杀",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"白色长衫",
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	
	([	"quest":	"丁春秋",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),

	([	"quest":	"唐云",
		"quest_type":	"杀",
		"exp_bonus":	150,
		"shen_type":	-1,
	]),

	([	"quest":	"方柔",
		"quest_type":	"杀",
		"exp_bonus":	150,
		"shen_type":	-1,
	]),

	([	"quest":	"孙不二",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	1,
	]),

	([	"quest":	"贾人达",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"[35m林太平[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	1,
	]),

	([	"quest":	"[1;35m段飞熊[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	0,
	]),

	([	"quest":	HIY"金花婆婆"NOR,
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"韦一笑",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"谢逊",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"殷天正",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	
	([	"quest":	HIR "魅影神靴" NOR,
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	HIY"纯金梅花"NOR,
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	HIG"寒玉沉香"NOR,
		"quest_type":	"寻",
		"exp_bonus":	110,
		"shen_type":	1,
	]),

	([	"quest":	"平等法王",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"勤修法王",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"掌火法王",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"常胜法王",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"智慧法王",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"大圣法王",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"信心法王",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"镇恶法王",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"正直法王",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),
	([	"quest":	"功德法王",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	0,
	]),

	([	"quest":	"三笑逍遥散",
		"quest_type":	"寻",
		"exp_bonus":	100,
		"shen_type":	1,
	]),
	([	"quest":	"鹅毛扇",
		"quest_type":	"寻",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
