#include <ansi.h>
inherit SKILL;

mapping *quest = ({
	([	"quest":	"吴钩",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),
	([	"quest":	"[1;33m夜莺[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	80,
		"shen_type":	0,
	]),

	([	"quest":	"[1;37m雪山飞狐狸[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	70,
		"shen_type":	-1,
	]),

	([	"quest":	"土匪首领",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"[33m南天霸[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"[30m卖艺人[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"[31m无情刀[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"陆大有",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
/*
	([	"quest":	"高根明",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
*/
	([	"quest":	"灰色长衫",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
/*
	([	"quest":	"紫霞秘笈",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"施戴子",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
*/
	([	"quest":	"[1;35m郭啸天[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"班察那",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"水烟阁司事",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"水烟阁司事帽",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"水烟阁司事褂",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"红衣武士",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"逄义",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"狮吼子",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"护寺喇嘛",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"宋青书",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"曲馥琪",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"火摺",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"赫造基",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"铁扇剑",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"[35m迷幻[2;37;0m[1;35m经纶[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"梁发",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"虞琼衣",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"[1;32m绿罗裙[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"慧名尊者",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"慧色尊者",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"青布镶边袈裟",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"老者",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"酒楼守卫",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"劳德诺",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"日后",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"天青丝衣",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"令狐冲",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"安惜迩",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"老村长",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"唐剑",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"程遥伽",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),


	([	"quest":	"白色道袍",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"王处一",
		"quest_type":	"杀",
		"exp_bonus":	100,
		"shen_type":	1,
	]),

	([	"quest":	"白猿",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"文善师太",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"文闲师太",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"文虚师太",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"[1;37m白衣镖师[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"[33m黄衣镖师[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"单刀",
		"quest_type":	"寻",
		"exp_bonus":	50,
		"shen_type":	1,
	]),

	([	"quest":	"[1;37m白色劲服[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"[33m黄色劲服[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"读千里",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"[31m红衣镖师[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"[31m红色劲服[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"文凌师太",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"文心师太",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"文怡师太",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"文月师太",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"[35m趟子手[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"少年刀客",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"[1;36m甑士隐[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"少年剑客",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"[34m趟子手[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"[35m阿珂[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"[1;36m白云飞[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"[1;35m温暖[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	0,
	]),

	([	"quest":	"[1;35m王动[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),

	([	"quest":	"[1;36m双儿[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"[1;37m苏芮[2;37;0m",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	-1,
	]),

	([	"quest":	"符敏仪",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"石嫂",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"张聆心",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"杨素兰",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"李大娘",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"竹剑",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"梅剑",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"兰剑",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"菊剑",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	
	([	"quest":	"封弓影",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"拔速台",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"冷若霜",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"拓跋",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	([	"quest":	"厉复生",
		"quest_type":	"杀",
		"exp_bonus":	90,
		"shen_type":	1,
	]),
	
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
