inherit SKILL;

mapping *quest = ({
        ([      "quest":                "三角麒麟",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "二角麒麟",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "铁少",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "雪蕊儿",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "姬九阴",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "葛伦",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "逍遥子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "柳淳风",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "骆云舟",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "於兰天武",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            800,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "潘军禅",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            700,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "萧辟尘",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            700,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "林忌",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "严廷殷",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            600,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "黄霸",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            600,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "黑袍公",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            600,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "白袍公",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            600,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "李信",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "常老大",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "安惜迩",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "赫造基",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "瑷伦",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "蓝止萍",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "玄智和尚",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "卜鹰",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "老张",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "陆得财",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "刘老农",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "土匪头领",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "吊睛白额大虫",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "赤松",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "胭松",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "县城官兵",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "上官钰翎",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            400,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "无名老妇",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            300,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "苗郁□",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            300,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "邢千慧",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            350,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "莫欣芳",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "朦胧鬼影",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "武官",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "酒楼守卫",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            100,
                "score" :               20
        ]),
        ([      "quest":                "天邪虎",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            350,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小金鼠",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "蓝筱薇",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "虞琼衣",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "龙韶吟",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "孙天灭",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "护山使者",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "独眼头陀",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "曲馥琪",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            350,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刘老头",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "看门卫兵",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            95,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "波斯奴",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            95,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "塔僧",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            105,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "黑衣人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "蓝雨梅",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "杀手",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "圆春",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "探春",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "惜春",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "迎春",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "野猪",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "芙云",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            150,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "梦玉楼",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "牧羊女",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小白兔",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "道士",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "疯老头子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "黑冠巨蟒",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清虚",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清灵",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "清平",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "水烟阁武士",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小兵",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "老兵",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "刘安禄",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            100,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "车马店老板",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "大绵羊",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            25,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "城卫",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "护寺藏尼",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "卧龙岗强盗",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            50,
                "score" :               20
        ]),
        ([      "quest":                "小翠",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            95,
                "pot_bonus":            59,
                "score" :               20
        ]),
        ([      "quest":                "趟子手",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            95,
                "pot_bonus":            59,
                "score" :               20
        ]),
        ([      "quest":                "贵公子",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "商人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            50,
                "pot_bonus":            5,
                "score" :               20
        ]),
        ([      "quest":                "岩蛭",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            55,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "肥岩蛭",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "跛僧人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            25,
                "score" :               20
        ]),
        ([      "quest":                "袭人",
                "quest_type":           "杀",
                "time":                 500,
                "exp_bonus":            52,
                "pot_bonus":            22,
                "score" :               20
        ]),
       ([      "quest":                "白棋子",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            30,
                "pot_bonus":            5,
                "score" :               30
        ]),
       ([      "quest":                "妖刀狗屠",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               10
        ]),
        ([      "quest":                "[1;36m吹雪残云靴[2;37;0m",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               10
        ]),
        ([      "quest":                "[1;36m吹雪残云衣[2;37;0m",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            200,
                "pot_bonus":            100,
                "score" :               10
        ]),
        ([      "quest":                "[1;36m吹雪残云巾[2;37;0m",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               10
        ]),
        ([      "quest":                "[1;36m吹雪残云带[2;37;0m",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               10
        ]),
       ([      "quest":                "[1;37m邪剑穿灵[2;37;0m",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            1500,
                "pot_bonus":            100,
                "score" :               10
        ]),
       ([      "quest":                "七星翻云靴",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               10
        ]),
       ([      "quest":                "天师道袍",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               10
        ]),
       ([      "quest":                "三清神冠",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            2000,
                "pot_bonus":            10
        ]),
       ([      "quest":                "[1;35m咒剑王□[2;37;0m",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               10
        ]),
       ([      "quest":                "[1;35m魔鞭翩珑[2;37;0m",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               30
        ]),
       ([      "quest":                "[1;35m紫霜血蝉衣[2;37;0m",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               30
        ]),
       ([      "quest":                "[1;33m软金束带[2;37;0m",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               30
        ]),
       ([      "quest":                "[1;32m穿花蛇影鞋[2;37;0m",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               30
        ]),
       ([      "quest":                "桃木剑",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               30
        ]),
       ([      "quest":                "大珍珠",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            300,
                "pot_bonus":            50,
                "score" :               30
        ]),        
       ([      "quest":                "垓下刀",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               30
        ]),
       ([      "quest":                "虞姬剑",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               30
        ]),
       ([      "quest":                "粗布鹅黄袍",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            1000,
                "pot_bonus":            100,
                "score" :               30
        ]),
       ([      "quest":                "黑布袍",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            100,
                "pot_bonus":            10,
                "score" :               30
        ]),
       ([      "quest":                "白布袍",
                "quest_type":           "寻",
                "time":                 900,
                "exp_bonus":            100,
                "pot_bonus":            10,
                "score" :               30
        ]),
       ([      "quest":                "秋风步法秘笈",
                "time":                 400,
                "quest_type":           "寻",
                "exp_bonus":            100,
                "pot_bonus":            10,
                "score" :               30
        ]),
       ([      "quest":                "蝶恋花剑法秘笈",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            10,
                "score" :               30
        ]),
       ([      "quest":                "短歌刀法秘笈",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            10,
                "score" :               30
        ]),
       ([      "quest":                "棋道秘笈",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            10,
                "score" :               30
        ]),
       ([      "quest":                "一剪梅花手秘笈",
                "quest_type":           "寻",
                "time":                 400,
                "exp_bonus":            100,
                "pot_bonus":            10,
                "score" :               30
        ]),
        ([      "quest":                "铁扇剑",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "[35m迷幻[2;37;0m[1;35m经纶[2;37;0m",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "[31m火 云 [1;34m战 甲[2;37;0m",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            35,
                "score" :               10
        ]),
        ([      "quest":                "[1;37mψ破 残 奇 剑ψ[2;37;0m",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            35,
                "score" :               10
        ]),
        ([      "quest":                "军刀",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            20,
                "score" :               10
        ]),
        ([      "quest":                "青铜道冠",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            20,
                "score" :               10
        ]),
        ([      "quest":                "印鉴",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            20,
                "score" :               10
        ]),
        ([      "quest":                "悟疾风劲竹书",
                "quest_type":           "寻",
                "exp_bonus":            25,
                "pot_bonus":            20,
                "score" :               10
        ]),
        ([      "quest":                "「嘉德文选」",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               10
        ]),
        ([      "quest":                "乌檀木刀",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "大饼",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            5,
                "score" :               10
        ]),
        ([      "quest":                "桃木箱",
                "quest_type":           "寻",
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "从寿衣撕下的布条",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "玉带冠",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "score" :               10
        ]),
        ([      "quest":                "轻罗绸衫",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "「白杨经」",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "银簪",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "「水龙图注」",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "「寒士列传」",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "「佾风斋诗集」",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "「乡书」",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "「古文志」",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "「说律」",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "「梁父文集」",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "「太公辩」",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "「九韬」",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
        ]),
        ([      "quest":                "钢刀",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            150,
                "score" :               10
        ]),
        ([      "quest":                "大金槌",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            800,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "短斧",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "score" :               10
        ]),
        ([      "quest":                "死岩蛭",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "护心镜",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               10
        ]),
        ([      "quest":                "熊皮短靴",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "碗",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            25,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "竹子",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "竹蜻蜓",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            2000,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "密函",
                "quest_type":           "寻",
                "time":                 500,
                "exp_bonus":            500,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "[1;36m绣花针[2;37;0m",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            500,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "玉瓷茶杯",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            2000,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "女儿红",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            200,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "柳玉刀",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            2000,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "青纱裙",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "冰玉戒指",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            2000,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "护身符",
                "quest_type":           "寻",
                "time":                 2500,
                "pot_bonus":            80,
                "score" :               10
        ]),
        ([      "quest":                "仙豆",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            2500,
                "pot_bonus":            50,
                "score" :               10
        ]),
        ([      "quest":                "夜行衣",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "竹扫把",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            500,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "菜刀",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "黑眼罩",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "阳经",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "馒头",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            250,
                "pot_bonus":            15,
                "score" :               10
        ]),
        ([      "quest":                "龟仙派武道服",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               10
        ]),
        ([      "quest":                "仙豆",
                "quest_type":           "寻",
                "time":                 250,
                "exp_bonus":            2000,
                "pot_bonus":            100,
                "score" :               10
        ]),
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
