#include <ansi.h>
inherit SKILL;

mapping *quest = ({
	
	([	"quest":	"渡肉长老",
		"quest_type":	"杀",
		"exp_bonus":	180,
		"shen_type":	1,
	]),
	([	"quest":	"於兰天武",
		"quest_type":	"杀",
		"exp_bonus":	180,
		"shen_type":	-1,
	]),
	
	([	"quest":	"[32m妖刀狗屠[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	180,
		"shen_type":	0,
	]),

	([	"quest":	"[1;33m怒龙锦胄[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	0,
	]),

	([	"quest":	"骆云舟",
		"quest_type":	"杀",
		"exp_bonus":	160,
		"shen_type":	1,
	]),
	([	"quest":	"[36m风泉之剑[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	0,
	]),

	([	"quest":	"达摩老祖",
		"quest_type":	"杀",
		"exp_bonus":	200,
		"shen_type":	1,
	]),

	([	"quest":	"鹤笔翁",
		"quest_type":	"杀",
		"exp_bonus":	200,
		"shen_type":	1,
	]),
	([	"quest":	"范遥",
		"quest_type":	"杀",
		"exp_bonus":	200,
		"shen_type":	1,
	]),
	([	"quest":	"鹿杖客",
		"quest_type":	"杀",
		"exp_bonus":	200,
		"shen_type":	1,
	]),

	([	"quest":	"木道人",
		"quest_type":	"杀",
		"exp_bonus":	200,
		"shen_type":	-1,
	]),
	([	"quest":	"[31m梅花点舌丹[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[36m天王补心丹[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	 "[34m九久元神散[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[1;37m怯邪守灵丹[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[35m降龙伏虎丸[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[1;31m银红蝉翼纱[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	 "[1;32m枫丹白露[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[1;36m唐伯虎画扇[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	 "[1;34m蓝晶瑞兽纽[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	 "[1;37m象牙佛像[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[30m六合琴谱[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[1;32m翡翠玉笛[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[1;35m紫烟天珠[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[1;37m御赐珍珠冠[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[1;37m汉白玉卧虎[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),
	([	"quest":	"[1;35m紫玉凤头钗[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	150,
		"shen_type":	0,
	]),

	
	
	
	
	
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
