inherit SKILL;

mapping *quest = ({
	
	([	"quest":	"欧阳敏",
		"quest_type":	"杀",
		"exp_bonus":	140,
		"shen_type":	-1,
	]),
	([	"quest":	"洪七公",
		"quest_type":	"杀",
		"exp_bonus":	140,
		"shen_type":	1,
	]),

	([	"quest":	"王重阳",
		"quest_type":	"杀",
		"exp_bonus":	140,
		"shen_type":	1,
	]),


	([	"quest":	"叫化鸡",
		"quest_type":	"寻",
		"exp_bonus":	140,
		"shen_type":	1,
	]),

	([	"quest":	"[32m玉竹杖[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	140,
		"shen_type":	1,
	]),

	([	"quest":	"渡难",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	1,
	]),
	([	"quest":	"渡劫",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	1,
	]),
	([	"quest":	"渡厄",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	1,
	]),

	([	"quest":	"张无忌",
		"quest_type":	"杀",
		"exp_bonus":	140,
		"shen_type":	1,
	]),

	([	"quest":	"白色长袍",
		"quest_type":	"寻",
		"exp_bonus":	140,
		"shen_type":	1,
	]),

	([	"quest":	"圣火令",
		"quest_type":	"寻",
		"exp_bonus":	140,
		"shen_type":	1,
	]),
	([	"quest":	"大红袈裟",
		"quest_type":	"寻",
		"exp_bonus":	140,
		"shen_type":	-1,
	]),

	([	"quest":	"灵空",
		"quest_type":	"杀",
		"exp_bonus":	140,
		"shen_type":	-1,
	]),
	([	"quest":        "[1;31m紫金杖[2;37;0m",
		"quest_type":   "寻",
		"exp_bonus":     140,
		"shen_type":	 -1,
		
	]),

	([	"quest":	"张三丰",
		"quest_type":	"杀",
		"exp_bonus":	140,
		"shen_type":	1,
	]),

	([	"quest":	"[32m真武剑[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	140,
		"shen_type":	1,
	]),

	([	"quest":	"夜帝",
		"quest_type":	"杀",
		"exp_bonus":	130,
		"shen_type":	1,
	]),

	([	"quest":	"瑷伦",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),

	([	"quest":	"[1;36m宝蓝缎衫[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	
	([	"quest":	"独孤峰",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	([	"quest":	"杨延庆",
		"quest_type":	"杀",
		"exp_bonus":	150,
		"shen_type":	-1,
	]),
	
	([	"quest":	"范松",
		"quest_type":	"杀",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	([	"quest":	"巨灵",
		"quest_type":	"杀",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	
	([	"quest":	"楚彤",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	([	"quest":	"赵鹤",
		"quest_type":	"杀",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	([	"quest":	"张乘云",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	([	"quest":	"张乘风",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	([	"quest":	"曲洋",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	([	"quest":	"花想容",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	([	"quest":	"[36m失魂魔叉[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	([	"quest":	"[32m温侯魔戟[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	([	"quest":	"[36m断玉魔钩[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	([	"quest":	"[35m灭世魔刀[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	([	"quest":	"[31m刺日魔枪[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	([	"quest":	"[34m毒龙魔鞭[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	([	"quest":	"[30m雷神魔锤[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	([	"quest":	"[31m破天魔斧[2;37;0m",
		"quest_type":	"寻",
		"exp_bonus":	130,
		"shen_type":	-1,
	]),
	([	"quest":        "铁毅",
		"quest_type":   "杀",
		"exp_bonus":	130,
		"shen_type":	1,
	]),
        ([      "quest":        "剑",
                "quest_type":   "寻",
                "exp_bonus":    110,
                "shen_type":    1,
        ]),

        ([      "quest":        "刀",
                "quest_type":   "寻",
                "exp_bonus":    110,
                "shen_type":    1,
        ]),

        ([      "quest":        "鞭",
                "quest_type":   "寻",
                "exp_bonus":    110,
                "shen_type":    1,
        ]),

        ([      "quest":        "锤",
                "quest_type":   "寻",
                "exp_bonus":    110,
                "shen_type":    1,
        ]),

        ([      "quest":        "叉",
                "quest_type":   "寻",
                "exp_bonus":    110,
                "shen_type":    1,
        ]),

        ([      "quest":        "箱子",
                "quest_type":   "寻",
                "exp_bonus":    110,
                "shen_type":    1,
        ]),

	([	"quest":	"苏星河",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	([	"quest":	"天山童姥",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	([	"quest":	"李秋水",
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),

	([	"quest":	HIG"黛绮丝"NOR,
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),

	([	"quest":	HIC"流云使"NOR,
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	([	"quest":	HIM"妙风使"NOR,
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	([	"quest":	HIG"辉月使"NOR,
		"quest_type":	"杀",
		"exp_bonus":	120,
		"shen_type":	-1,
	]),
	

        ([      "quest":        "九转熊蛇丸",
                "quest_type":   "寻",
                "exp_bonus":    110,
                "shen_type":    1,
        ]),

        ([      "quest":        HIM "天蚕衣" NOR,
                "quest_type":   "寻",
                "exp_bonus":    110,
                "shen_type":    1,
        ]),

        ([      "quest":        "铁管",
                "quest_type":   "寻",
                "exp_bonus":    110,
                "shen_type":    1,
        ]),

        ([      "quest":        "绣花针",
                "quest_type":   "寻",
                "exp_bonus":    60,
                "shen_type":    1,
        ]),

});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}
