#include <ansi.h>
inherit SKILL;

mapping *quest = ({

        ([      "quest":        "渡肉长老",
                "quest_type":   "杀",
                "exp_bonus":    180,
                "shen_type":    1,
        ]),
      ([      "quest":        "赵敏",
              "quest_type":   "杀",
              "exp_bonus":    180,
              "shen_type":    0,
      ]),
        ([      "quest":        "於兰天武",
                "quest_type":   "杀",
                "exp_bonus":    180,
                "shen_type":    -1,
        ]),
        ([      "quest":        "辛十三娘",
                                "quest_type":   "杀",
                                "exp_bonus":    180,
                                "shen_type":    -1,
        ]),

          ([      "quest":       GRN "妖刀狗屠" NOR,
                "quest_type":   "寻",
                "exp_bonus":    180,
                "shen_type":    0,
        ]),

        ([      "quest":        "鹤笔",
                                "quest_type":   "寻",
                                "exp_bonus":    100,
                                "shen_type":    0,
                  ]),

                  ([      "quest":        HIC"鹿杖"NOR,
                                "quest_type":   "寻",
                                "exp_bonus":    100,
                                "shen_type":    0,
                   ]),

        ([      "quest":        HIY"怒龙锦胄"NOR,
                "quest_type":   "寻",
                "exp_bonus":    130,
                "shen_type":    0,
        ]),

        ([      "quest":        "骆云舟",
                "quest_type":   "杀",
                "exp_bonus":    160,
                "shen_type":    1,
        ]),
        ([      "quest":        CYN"风泉之剑"NOR,
                "quest_type":   "寻",
                "exp_bonus":    130,
                "shen_type":    0,
        ]),

        ([      "quest":        "达摩老祖",
                "quest_type":   "杀",
                "exp_bonus":    200,
                "shen_type":    1,
        ]),

        ([      "quest":        "鹤笔翁",
                "quest_type":   "杀",
                "exp_bonus":    200,
                "shen_type":    1,
        ]),
        ([      "quest":        "范遥",
                "quest_type":   "杀",
                "exp_bonus":    200,
                "shen_type":    1,
        ]),
        ([      "quest":        "鹿杖客",
                "quest_type":   "杀",
                "exp_bonus":    200,
                "shen_type":    1,
        ]),

        ([      "quest":        "木道人",
                "quest_type":   "杀",
                "exp_bonus":    200,
                "shen_type":    -1,
        ]),
        ([      "quest":        CYN"天王补心丹"NOR,
                "quest_type":   "寻",
                "exp_bonus":    150,
                "shen_type":    0,
        ]),
        ([      "quest":        HIC"唐伯虎画扇"NOR,
                "quest_type":   "寻",
                "exp_bonus":    150,
                "shen_type":    0,
        ]),
        ([      "quest":         HIB"御赐珍珠冠"NOR,
                "quest_type":   "寻",
                "exp_bonus":    150,
                "shen_type":    0,
        ]),
        ([      "quest":        HIW"汉白玉天珠"NOR,
                "quest_type":   "寻",
                "exp_bonus":    150,
                "shen_type":    0,
        ]),
        ([      "quest":        HIR"达摩袈裟"NOR,
                "quest_type":   "寻",
                "exp_bonus":    150,
                "shen_type":    0,
        ]),
        ([      "quest":        "翁四先生的钢拐",
                "quest_type":   "寻",
                "exp_bonus":    150,
                "shen_type":    0,
        ]),

        ([      "quest":        HIY"飞去来兮"NOR,
                "quest_type":   "寻",
                "exp_bonus":    150,
                "shen_type":    0,
        ]),
        ([      "quest":        HIM"无忧情丝"NOR,
                "quest_type":   "寻",
                "exp_bonus":    150,
                "shen_type":    0,
        ]),
        ([      "quest":        "寒光",
                "quest_type":   "寻",
                "exp_bonus":    150,
                "shen_type":    0,
        ]),
        ([      "quest":        HIR"霸王枪"NOR,
                                "quest_type":   "寻",
                                "exp_bonus":    150,
                                "shen_type":    0,
        ]),
        ([      "quest":        "幽冥大鹏",
                "quest_type":   "杀",
                "exp_bonus":    180,
                "shen_type":    1,
        ]),
        ([      "quest":        "宇文秀",
                "quest_type":   "杀",
                "exp_bonus":    180,
                "shen_type":    1,
        ]),
        ([      "quest":        "翁四先生的厉鬼",
                "quest_type":   "杀",
                "exp_bonus":    180,
                "shen_type":    1,
        ]),
                ([      "quest":        "张天师",
                "quest_type":   "杀",
                "exp_bonus":    180,
                "shen_type":    1,
        ]),
        ([      "quest":        GRN"风吹雨"NOR,
                "quest_type":   "杀",
                "exp_bonus":    180,
                "shen_type":    1,
        ]),
        ([      "quest":        MAG"艳无忧"NOR,
                "quest_type":   "杀",
                "exp_bonus":    180,
                "shen_type":    1,
        ]),
        ([      "quest":        MAG"艳无忧"NOR,
                "quest_type":   "杀",
                "exp_bonus":    180,
                "shen_type":    1,
        ]),
        ([      "quest":        "赤松",
                "quest_type":   "杀",
                "exp_bonus":    180,
                "shen_type":    1,
        ]),
        ([      "quest":        "圆真",
                                "quest_type":   "杀",
                                "exp_bonus":    180,
                                "shen_type":    1,
        ]),
        ([      "quest":        HIM"旋芒宝剑"NOR,
                "quest_type":   "寻",
                "exp_bonus":    180,
                "shen_type":    1,
        ]),
});


mapping query_quest()
{
        return quest[random(sizeof(quest))];
}

